name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: v1.x

    name: Test with Deno ${{ matrix.deno }}
    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        with:
          deno-version: ${{ matrix.deno }}

      - name: Check format
        run: deno fmt --check

      - name: Run tests
        run: deno test --allow-net
